# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='suggestion',
            new_name='comment',
        ),
        migrations.AlterField(
            model_name='people',
            name='email',
            field=models.EmailField(max_length=20),
        ),
    ]
